# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'js06_1920.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_js06_1920(object):
    def setupUi(self, js06_1920):
        js06_1920.setObjectName("js06_1920")
        js06_1920.resize(1920, 1080)
        js06_1920.setStyleSheet("#js06_1920\n"
"{\n"
"    background-color:rgb(22,32,42);\n"
"}")
        self.title_label = QtWidgets.QLabel(js06_1920)
        self.title_label.setGeometry(QtCore.QRect(20, 20, 1880, 90))
        font = QtGui.QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("#title_label\n"
"{\n"
"    background-color:rgb(27,49,70);\n"
"    color:rgb(28,136,227);\n"
"}")
        self.title_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label.setObjectName("title_label")
        self.pushButton = QtWidgets.QPushButton(js06_1920)
        self.pushButton.setGeometry(QtCore.QRect(1830, 35, 57, 58))
        self.pushButton.setStyleSheet("\n"
"#pushButton\n"
"{\n"
"    background-image: url(C:/Users/user/Desktop/settings.png);\n"
"    border:0px;\n"
"}\n"
"#pushButton:pressed\n"
"{\n"
"    background-image: url(C:/Users/user/Desktop/settings_on.png);\n"
"    background-color:rgb(27,49,70);\n"
"}\n"
"#pushButton:hover\n"
"{\n"
"    background-image: url(C:/Users/user/Desktop/settings_on.png);\n"
"    background-color:rgb(27,49,70);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.image_label = QtWidgets.QLabel(js06_1920)
        self.image_label.setGeometry(QtCore.QRect(20, 110, 1880, 410))
        self.image_label.setStyleSheet("#image_label\n"
"{\n"
"    background-color:rgb(25,39,52);\n"
"}\n"
"")
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.visibility_label = QtWidgets.QLabel(js06_1920)
        self.visibility_label.setGeometry(QtCore.QRect(20, 530, 1290, 90))
        font = QtGui.QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.visibility_label.setFont(font)
        self.visibility_label.setStyleSheet("#visibility_label\n"
"{\n"
"    background-color:rgb(27,49,70);\n"
"    color:rgb(255,255,255);\n"
"}")
        self.visibility_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.visibility_label.setObjectName("visibility_label")
        self.graph_label = QtWidgets.QLabel(js06_1920)
        self.graph_label.setGeometry(QtCore.QRect(20, 620, 1290, 440))
        self.graph_label.setStyleSheet("#graph_label\n"
"{\n"
"    background-color:rgb(25,39,52);\n"
"}\n"
"")
        self.graph_label.setText("")
        self.graph_label.setObjectName("graph_label")
        self.graph_pushButton = QtWidgets.QPushButton(js06_1920)
        self.graph_pushButton.setGeometry(QtCore.QRect(1230, 550, 57, 56))
        self.graph_pushButton.setAutoFillBackground(False)
        self.graph_pushButton.setStyleSheet("\n"
"#graph_pushButton\n"
"{\n"
"    background-image: url(C:/Users/user/Desktop/graph.png);\n"
"    border:0px;\n"
"}\n"
"")
        self.graph_pushButton.setText("")
        self.graph_pushButton.setAutoDefault(True)
        self.graph_pushButton.setDefault(True)
        self.graph_pushButton.setFlat(True)
        self.graph_pushButton.setObjectName("graph_pushButton")
        self.time_label = QtWidgets.QLabel(js06_1920)
        self.time_label.setGeometry(QtCore.QRect(1330, 530, 570, 90))
        font = QtGui.QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("#time_label\n"
"{\n"
"    background-color:rgb(27,49,70);\n"
"    color:rgb(220,220,220);\n"
"}")
        self.time_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.time_label.setObjectName("time_label")
        self.clock_pushButton = QtWidgets.QPushButton(js06_1920)
        self.clock_pushButton.setGeometry(QtCore.QRect(1830, 550, 54, 54))
        self.clock_pushButton.setAutoFillBackground(False)
        self.clock_pushButton.setStyleSheet("\n"
"#clock_pushButton\n"
"{\n"
"    background-image: url(C:/Users/user/Desktop/clock.png);\n"
"    border:0px;\n"
"}\n"
"")
        self.clock_pushButton.setText("")
        self.clock_pushButton.setAutoDefault(True)
        self.clock_pushButton.setDefault(True)
        self.clock_pushButton.setFlat(True)
        self.clock_pushButton.setObjectName("clock_pushButton")
        self.real_time_label = QtWidgets.QLabel(js06_1920)
        self.real_time_label.setGeometry(QtCore.QRect(1330, 620, 570, 120))
        self.real_time_label.setStyleSheet("#real_time_label\n"
"{\n"
"    background-color:rgb(25,39,52);\n"
"}\n"
"")
        self.real_time_label.setText("")
        self.real_time_label.setObjectName("real_time_label")
        self.c_vis_title_label = QtWidgets.QLabel(js06_1920)
        self.c_vis_title_label.setGeometry(QtCore.QRect(1330, 750, 570, 90))
        font = QtGui.QFont()
        font.setFamily("NanumGothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.c_vis_title_label.setFont(font)
        self.c_vis_title_label.setStyleSheet("#c_vis_title_label\n"
"{\n"
"    background-color:rgb(27,49,70);\n"
"    color:rgb(220,220,220);\n"
"}")
        self.c_vis_title_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.c_vis_title_label.setObjectName("c_vis_title_label")
        self.c_vis_label = QtWidgets.QLabel(js06_1920)
        self.c_vis_label.setGeometry(QtCore.QRect(1330, 840, 570, 220))
        self.c_vis_label.setStyleSheet("#c_vis_label\n"
"{\n"
"    background-color:rgb(25,39,52);\n"
"}\n"
"")
        self.c_vis_label.setText("")
        self.c_vis_label.setObjectName("c_vis_label")
        self.vis_pushButton = QtWidgets.QPushButton(js06_1920)
        self.vis_pushButton.setGeometry(QtCore.QRect(1840, 770, 48, 48))
        self.vis_pushButton.setAutoFillBackground(False)
        self.vis_pushButton.setStyleSheet("\n"
"#vis_pushButton\n"
"{\n"
"    background-image: url(C:/Users/user/Desktop/vis.png);\n"
"    border:0px;\n"
"}\n"
"")
        self.vis_pushButton.setText("")
        self.vis_pushButton.setAutoDefault(True)
        self.vis_pushButton.setDefault(True)
        self.vis_pushButton.setFlat(True)
        self.vis_pushButton.setObjectName("vis_pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(js06_1920)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 110, 1881, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticallayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticallayout.setContentsMargins(0, 0, 0, 0)
        self.verticallayout.setObjectName("verticallayout")

        self.retranslateUi(js06_1920)
        QtCore.QMetaObject.connectSlotsByName(js06_1920)

    def retranslateUi(self, js06_1920):
        _translate = QtCore.QCoreApplication.translate
        js06_1920.setWindowTitle(_translate("js06_1920", "Form"))
        self.title_label.setText(_translate("js06_1920", "   Monitoring"))
        self.visibility_label.setText(_translate("js06_1920", "   Visibility"))
        self.time_label.setText(_translate("js06_1920", "   Current time"))
        self.c_vis_title_label.setText(_translate("js06_1920", "   Visibility"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    js06_1920 = QtWidgets.QWidget()
    ui = Ui_js06_1920()
    ui.setupUi(js06_1920)
    js06_1920.show()
    sys.exit(app.exec_())
